services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./docker_env/otel-collector/otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 4318:4318

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 16686:16686 # msと同じポートなので変えたい
